# Generated by Django 6.0.7 on 2026-07-19 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottleState',
            fields=[
                ('scope_hash', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('failure_count', models.PositiveSmallIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'login throttle state',
                'verbose_name_plural': 'login throttle states',
            },
        ),
    ]
